### ISSUE TITLE
Unable to convert some PDB files

### ISSUE THREAD

**Issue by filipsPL** [m4rx9/rna-pdb-tools#1]
I observe some problems with making PDB files SimRNA ready. E.g., for this command:

`yapdb_parser.py --get_simrna_ready pdb-clean.pdb`

I get an error:
```
HEADER Generated with yapdb_parser, version: unknown (https://github.com/m4rx9/rna-pdb-tools) Mon Apr 18 15:53:52 2016
/usr/lib/python2.7/dist-packages/Bio/PDB/StructureBuilder.py:85: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 635.
  PDBConstructionWarning)
Traceback (most recent call last):
  File "/home/fstefaniak/gitlab/coarse-grain-potential/other/rna-pdb-tools/yapdb_parser.py", line 135, in <module>
    s.get_simrna_ready()
  File "/home/fstefaniak/gitlab/coarse-grain-potential/other/rna-pdb-tools/pdb_parser_lib.py", line 666, in get_simrna_ready
    x = r["O5'"]
  File "/usr/lib/python2.7/dist-packages/Bio/PDB/Entity.py", line 38, in __getitem__
    return self.child_dict[id]
KeyError: "O5'"
```

This seems to happen quite frequently in my dataset :frowning: 

Input pdb file attached (zipped)
[a.zip](https://github.com/m4rx9/rna-pdb-tools/files/223878/a.zip)

**Comment by m4rx9** [comment]
It should be fixed now.

```
➜  rna_pdb_filip yapdb_parser.py --get_simrna_ready pdb-clean.pdb > out.pdb
/Library/Python/2.7/site-packages/Bio/PDB/StructureBuilder.py:87: PDBConstructionWarning: WARNING: Chain A is discontinuous at line 635.
  PDBConstructionWarning)

➜  rna_pdb_filip yapdb_parser.py 
usage: yapdb_parser ver: b528a29 ...
```
version b528a29

**Comment by filipsPL** [comment]
Thanks! :beer: :+1:
